version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:025887537613:task-definition/hello-world:2"
        LoadBalancerInfo:
          ContainerName: "hello-world"
          ContainerPort: "80"
        PlatformVersion: "LATEST"